#! /bin/sh

cleanup () {
  trap - EXIT
  ../bin/erlrc-eval erlrcdowngrade$$ 'init:stop ()' >/dev/null 2>/dev/null
  rm -rf flass$$
  rm -rf erlrcdowngrade$$
}

trap cleanup EXIT
set -e

{
ERLRC_ROOT=`pwd`/flass$$
export ERLRC_ROOT

rm -rf erlrcdowngrade$$
mkdir -p erlrcdowngrade$$/erlrctest-0.0.1/ebin

rm -rf flass$$
mkdir -p flass$$/nodes/
mkdir -p flass$$/applications/

erl -name erlrcdowngrade$$ -setcookie flass$$ -noshell -noinput -pa ../.eunit/ -erlrc root_dir \"flass$$\" -eval '
  ok = application:load (erlrc),
  receive after infinity -> ok end
' -s erlang halt &

printf "%s" "flass$$" > flass$$/nodes/erlrcdowngrade$$
printf "%s" "turg" > flass$$/nodes/node_not_started

erl -name erlrcdowngradefindah$$ -setcookie flass$$ -noshell -noinput -eval "
  [ Host ] = tl (string:tokens (atom_to_list (node ()), \"@\")),
  Other = list_to_atom (atom_to_list (erlrcdowngrade$$) ++ \"@\" ++ Host),
  G = fun (_, 0) -> failed;
          (F, N) -> case net_adm:ping (Other) of pong -> ok; 
                                                 pang -> timer:sleep (50),
                                                         F (F, N - 1)
                    end
      end,
  ok = G (G, 100)" -s erlang halt 

perl -pe 's%vsn, "0.0.0"%vsn, "0.0.1"% ;' erlrctest.app > erlrcdowngrade$$/erlrctest-0.0.1/ebin/erlrctest.app 
cp ../.eunit/erlrctest.beam erlrcdowngrade$$/erlrctest-0.0.1/ebin/

set +e
echo "***** the following ERROR_REPORT is expected *****"
../bin/erlrc-downgrade erlrctest 0.0.0 0.0.1 && exit 1
echo "***** subsequent ERROR_REPORTs are not expected *****"
set -e
../bin/erlrc-downgrade erlrctest 0.0.1 0.0.0 ./erlrcdowngrade$$/erlrctest-0.0.1 ./erlrcdowngrade$$/erlrctest-0.0.0
../bin/erlrc-eval                                                        \
  erlrcdowngrade$$                                                         \
  "{ value, { erlrctest, _, \"0.0.1\" } } = 
    lists:keysearch (erlrctest, 1, application:which_applications ())" > /dev/null

mkdir -p erlrcdowngrade$$/erlrctest-0.0.0/ebin
cp erlrctest.app ../.eunit/erlrctest.beam erlrcdowngrade$$/erlrctest-0.0.0/ebin 

../bin/erlrc-downgrade erlrctest 0.0.0 0.0.1 ./erlrcdowngrade$$/erlrctest-0.0.0 ./erlrcdowngrade$$/erlrctest-0.0.1
../bin/erlrc-eval                                                        \
  erlrcdowngrade$$                                                         \
  "{ value, { erlrctest, _, \"0.0.0\" } } = 
    lists:keysearch (erlrctest, 1, application:which_applications ())" > /dev/null
../bin/erlrc-downgrade erlrctest 0.0.0 0.0.1 ./erlrcdowngrade$$/erlrctest-0.0.0 ./erlrcdowngrade$$/erlrctest-0.0.1 
../bin/erlrc-stop erlrctest 0.0.0 ./erlrcdowngrade$$/erlrctest-0.0.0
../bin/erlrc-downgrade erlrctest 0.0.0 0.0.1 ./erlrcdowngrade$$/erlrctest-0.0.0 ./erlrcdowngrade$$/erlrctest-0.0.1 
../bin/erlrc-eval                                                        \
  erlrcdowngrade$$                                                         \
  "{ value, { erlrctest, _, \"0.0.0\" } } = 
    lists:keysearch (erlrctest, 1, application:which_applications ())" > /dev/null
} > test-downgrade.out 2>&1

exit 0
